OS-8565 zut needs manifest and driver config updates
TritonDataCenter/illumos-joyent pull request #478
Opened 2024-08-09 14:00 UTC by tsoome

zfstests need to access /dev/zut.

Once present:
ztest@smartos:~$ /opt/zfs-tests/bin/zfstest -T casenorm                         
Test: /opt/zfs-tests/tests/functional/casenorm/setup (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/case_all_values (run as root) [00:01] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/norm_all_values (run as root) [00:02] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/sensitive_none_lookup (run as root) [00:01] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/sensitive_none_delete (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/sensitive_formd_lookup (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/sensitive_formd_delete (run as root) [00:01] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/insensitive_none_lookup (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/insensitive_none_delete (run as root) [00:01] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/insensitive_formd_lookup (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/insensitive_formd_delete (run as root) [00:02] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/mixed_none_lookup (run as root) [00:01] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/mixed_none_lookup_ci (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/mixed_none_delete (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/mixed_formd_lookup (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/mixed_formd_lookup_ci (run as root) [00:00] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/mixed_formd_delete (run as root) [00:01] [PASS]
Test: /opt/zfs-tests/tests/functional/casenorm/cleanup (run as root) [00:00] [PASS]

Results Summary
PASS      18

Running Time:   00:00:20
Percent passed: 100.0%
Log directory:  /var/tmp/test_results/20240809T132049
ztest@smartos:~$

2024-08-09 14:16 UTC, danmcd requested changes
I think this should be done in `smartos-test.sh` where we have it do the add_drv(8) and friends Just for the test.  I know the module's there already...

Actually, maybe it should be put into the tests-tar.  There are other test-only drivers that might need this treatment as well.

2024-08-09 15:09 UTC, danmcd commented
> Actually, maybe it should be put into the tests-tar. There are other test-only drivers that might need this treatment as well.

`zut` actually ALREADY IS in the tests-tar.

Prior art here includes also-in-upstream ksensor tests, and our own downstream diffs for BHYVE testing (see https://www.illumos.org/issues/14886 for my screed on the inconsistency upstream about this).  We need to do the same here for zut. The `zfs_test_check`() function in `smartos-test.sh` may be a good place to put the add_drv, etc. etc.

2024-08-09 17:37 UTC, tsoome commented
> > Actually, maybe it should be put into the tests-tar. There are other test-only drivers that might need this treatment as well.
> 
> `zut` actually ALREADY IS in the tests-tar.
> 
> Prior art here includes also-in-upstream ksensor tests, and our own downstream diffs for BHYVE testing (see https://www.illumos.org/issues/14886 for my screed on the inconsistency upstream about this). We need to do the same here for zut. The `zfs_test_check`() function in `smartos-test.sh` may be a good place to put the add_drv, etc. etc.

did add add_drv/rem_drv into smartos-test.

2024-08-09 18:07 UTC, danmcd approved these changes
Change seems fine.  Has it been tested?  Do you want it tested?  I approve, but IA is blocked on the testing for now.

2024-08-09 18:28 UTC, tsoome commented
> Change seems fine. Has it been tested? Do you want it tested? I approve, but IA is blocked on the testing for now.

smartos-test is running atm, so it will take some time to get results.

2024-08-10 17:04 UTC, tsoome commented
zfstests run as part of smartos-test:
Results Summary
PASS	 1278
FAIL	  13
SKIP	   4
KILLED	   1

Running Time:	04:23:22
Percent passed:	98.6%
Log directory:	/var/tmp/test_results/20240809T175615

[root@smartos /var/tmp/test_results]# modinfo | grep zut
[root@smartos /var/tmp/test_results]# 

The number of failed tests is further down and zut is unloaded.

2024-08-10 19:14 UTC, danmcd commented
Make sure Jira ticket has copy of the test notes above.

2024-08-10 19:57 UTC, tsoome commented
> Make sure Jira ticket has copy of the test notes above.

done.

2024-08-10 20:00 UTC, merged